### ISSUE TITLE
Menees.Common - Library inclusion causes Windows Store deployment failure

### ISSUE THREAD

**Issue by jsiemensLatitudegeo** [menees/Libraries#2]
Library is not useable in a Windows Store deployment for a UWP app.

Due to the usage of GetForegroundWindow in NativeMethods, Windows app (UWP) store deployment fails with the following message:

    <REQUIREMENT NUMBER="15" TITLE="Supported API test" RATIONALE="The application should only refer to the APIs allowed by the Windows SDK for Windows Store Apps.">
      <TEST INDEX="38" NAME="Supported APIs" DESCRIPTION="Windows Store App must only use supported platform APIs." EXECUTIONTIME="00h:13m:43s.99ms" OPTIONAL="FALSE">
        <MESSAGES>
          <MESSAGE TEXT="API GetForegroundWindow in user32.dll is not supported for this application type. GeocortexMobileViewer.dll calls this API." />
        </MESSAGES>
        <RESULT><![CDATA[FAIL]]></RESULT>
      </TEST>
    </REQUIREMENT>

For anyone else facing this issue, and wanting to use Menees.Diffs, we switched over to use spkl.Diffs instead, which provides the same algorithm implementation.

**Comment by menees** [comment]
Sorry about that. The fix is in the [v4.9.11 NuGet package](https://www.nuget.org/packages/Menees.Diffs/).

Menees.Common didn't really need the dependency on GetForegroundWindow. I've moved that call into the Menees.Windows library now. The Menees.Diffs library only depends on Menees.Common, so hopefully it'll work in a UWP app now. I don't have a UWP app to test it in, and I'm too lazy to create one and mess with Windows Store deployment for verification.
